name: PocketVR
options:
  projectFormat: xcode26_0
  xcodeVersion: "26.0"
  bundleIdPrefix: com.zaiahgaming
  deploymentTarget:
    iOS: "26.0"
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  PocketVR:
    type: application
    platform: iOS
    sources:
      - path: PocketVR
    resources:
      - path: PocketVR/Resources/transcript.txt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zaiahgaming.pocketvr
        PRODUCT_NAME: PocketVR
        INFOPLIST_FILE: PocketVR/Resources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets: []
