plugins { id 'com.android.application' }
android {
    namespace 'com.zaiahgaming.pocketvr'
    compileSdk 35
    defaultConfig { applicationId 'com.zaiahgaming.pocketvr'; minSdk 26; targetSdk 35; versionCode 2; versionName '1.1' }
    buildTypes { release { signingConfig signingConfigs.debug; minifyEnabled false } }
}
